// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCob2HyNuY_A_Q-pBvV6KV9j7beEZ_nxSQ',
    appId: '1:107595354388:web:eb284a1106e8ed94277201',
    messagingSenderId: '107595354388',
    projectId: 'my-chat-snepchat',
    authDomain: 'my-chat-snepchat.firebaseapp.com',
    storageBucket: 'my-chat-snepchat.appspot.com',
    measurementId: 'G-HGRJMY6FN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAllDAaXeEYP2WGnffDIvIn1tbITeGNCOk',
    appId: '1:107595354388:android:a728098ec5e738a4277201',
    messagingSenderId: '107595354388',
    projectId: 'my-chat-snepchat',
    storageBucket: 'my-chat-snepchat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBubaz4howbTWUgw0oiBmEYyDr858qU0iY',
    appId: '1:107595354388:ios:38d5a34ec6bbd886277201',
    messagingSenderId: '107595354388',
    projectId: 'my-chat-snepchat',
    storageBucket: 'my-chat-snepchat.appspot.com',
    iosBundleId: 'com.example.myChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBubaz4howbTWUgw0oiBmEYyDr858qU0iY',
    appId: '1:107595354388:ios:38d5a34ec6bbd886277201',
    messagingSenderId: '107595354388',
    projectId: 'my-chat-snepchat',
    storageBucket: 'my-chat-snepchat.appspot.com',
    iosBundleId: 'com.example.myChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCob2HyNuY_A_Q-pBvV6KV9j7beEZ_nxSQ',
    appId: '1:107595354388:web:6f8e3fe9e71595f6277201',
    messagingSenderId: '107595354388',
    projectId: 'my-chat-snepchat',
    authDomain: 'my-chat-snepchat.firebaseapp.com',
    storageBucket: 'my-chat-snepchat.appspot.com',
    measurementId: 'G-SLFHDKTBKQ',
  );
}
